# Generated by Django 3.1.2 on 2020-11-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
